try{
    console.lo(kk)
}catch(err){
    console.log(err)
    console.log(err.name)
    console.log(err.message)
}